-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Tempo de geração: 11/06/2025 às 11:29
-- Versão do servidor: 10.4.32-MariaDB
-- Versão do PHP: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `teste`
--

-- --------------------------------------------------------

--
-- Estrutura para tabela `racas`
--

CREATE TABLE `racas` (
  `ID` int(11) NOT NULL,
  `NOME` varchar(100) NOT NULL,
  `DESCRICAO` text DEFAULT NULL,
  `CARACTERISTICAS` text DEFAULT NULL,
  `IMAGEM_URL` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Despejando dados para a tabela `racas`
--

INSERT INTO `racas` (`ID`, `NOME`, `DESCRICAO`, `CARACTERISTICAS`, `IMAGEM_URL`) VALUES
(2, 'Pinscher', 'O Pinscher já existia em grande número,na virada do século e o livro de criação de 1925 registrou não menos que 1300 inscrições. Como no Pinscher Alemão, das inúmeras variedades de cores existentes na época, apenas as cores preta com marcações mais claras e vermelha, do sólido ao amarronzado, foram selecionadas para a criação.', 'É um cão de porte pequeno, pelagem curta e seu peso em média é de 4 a 6kg. Em sua maioria, são cachorros agitados e que precisam de atenção e apesar de existir uma má fama do temperamento dos pinschers, isso tudo vai depender de como ele foi criado, afinal, os pinschers também podem ser uma raça amorosa, que gosta de atenção e que também gosta de conviver com crianças.', 'img/pinscher.jpg'),
(3, 'Chihuahua', 'O Chihuahua é considerado a menor raça do mundo; recebe o nome do maior estado da República Mexicana, onde se supõe que viveu de forma selvagem e foi capturado e domesticado pelos indígenas durante a época da civilização “Tolteca”.', 'Seu tipo de pelagem é curto, e além disso, pode ser encontrado de diversas tonalidades. O peso ideal para um Chiuaua é entre 1,5kg e 2,5kg, sua alimentação deve ser saudável e repleta de proteínas para manter os músculos fortes. É um cachorro mega resistente, quase não fica doente desde que receba os cuidados necessários, ele é rápido, alerta e inquieto, além de muito inteligente, o que o torna mais fácil de ser treinado.', 'img/chihuahua.jpg'),
(4, 'Fox Paulistinha', 'O Fox Paulistinha é originário de terras brasileiras. Segundo os especialistas, a raça é resultado do cruzamento de cães trazidos da Europa , como o jack russel e o fox terrier, com animais já encontrados aqui. É uma das poucas raças reconhecidas como brasileira.', 'Seu tipo de pelagem é curto, e além disso, pode ser encontrado de diversas tonalidades. O Fox Paulistinha é um cachorro de porte pequeno e que tem sua pelagem média, seu peso é em média de 6 a 10kg. É um cão muito elétrico, mas que também oferece muito amor aos seus tutores, além de ser bastante paciente com crianças.', 'img/foxpaulistinha.jpg'),
(5, 'Border Terrier', 'O Border Terrier surgiu no século XVIII, na Grã-Bretanha, mais especificamente em uma região denominada Cheviot Hills (fronteira entre Escócia e Inglaterra). Trata-se de uma área rural, onde os fazendeiros sofriam bastante com ataques de raposas. Sendo assim, ele era criado para caçar esses animais.', 'É um cachorro de porte pequeno, mas com musculatura forte, sua pelagem é curta e as cores de pelos mais comuns que são vistas são: vermelho, cinzento, castanho e trigo. Os machos costumam pesar entre 5 a 7,1kg e as fêmeas 5,1 a 6,4kg.', 'img/borderterrier.jpg'),
(6, 'Galgo Italiano', 'A raça está presente no mundo há mais de 2 mil anos. Alguns registros apontam para as primeiras aparições do pet no Antigo Egito, Grécia e Turquia. No início do século 5, depois de se disseminar pelo sul da Europa, o Galgo chegou à Itália, se consolidando no país por meio dos nobres.', 'A raça é de porte pequeno com a pelagem curta. é um pet bastante rápido e que está sempre atento, é um cão que gosta de atenção e não se adapta tão bem a ambientes frios, a convivência dele com outros animais é bem tranquila, o Galgo gosta bastante de crianças, mas também não tem muita paciência caso a criança for indisciplinada.', 'img/galgoitaliano.jpg'),
(7, 'Jack Russell', 'Assim como muitos outros Terriers, o Jack Russell surgiu na Inglaterra, no final do século 20. O “criador” da raça, um reverendo inglês chamado John “Jack” Russell, era apaixonado por caçar raposas e passou a criar seus cães para serem caçadores em que ele poderia confiar.', 'Raça de porte pequeno, com o pelo um pouco mais curto. É um cachorro que exige muita atenção de seu dono, principalmente quando o assunto é gastar energia, que é o que ele tem de sobra, é moderadamente sociável mas é bastante adaptável aos lugares.', 'img/jackrussell.jpg'),
(8, 'Dachshund', 'O Dachshund, também conhecido como \"cão salsicha\", tem origem na Alemanha e foi desenvolvido por volta do século XVII com o objetivo de caçar texugos — seu nome inclusive significa \"cão texugo\" em alemão.', 'De personalidade marcante, o Dachshund é corajoso, determinado e muitas vezes teimoso. Ele é muito apegado aos donos e costuma ser desconfiado com estranhos, o que o torna um bom cão de alerta.  Com o tempo, a raça ganhou popularidade não só como cão de caça, mas também como animal de companhia, sendo até mesmo bastante apreciada pela nobreza europeia.', 'img/dachshund.jpg'),
(9, 'Portuguese Podengo Pequeno', 'O Portuguese Podengo Pequeno é uma das raças mais antigas de Portugal, com raízes que remontam à época dos fenícios e romanos. Utilizado tradicionalmente na caça de coelhos, este cão se destaca por sua agilidade, visão e olfato aguçados.', 'É uma raça muito ativa, que precisa de espaço para correr ou passeios frequentes, apesar de se adaptar bem à vida em apartamentos, se for exercitado corretamente. Segundo o Petz, é um cão leal e brincalhão com a família, mas pode ser reservado com estranhos.', 'img/portuguesepodengopequeno.jpg'),
(10, 'Bulldog Francês', 'Originou-se por volta do século XIX, quando operários da indústria têxtil britânica trouxeram versões menores do Bulldog Inglês para a França durante a Revolução Industrial. Esses cães se tornaram populares como ratters e companheiros em Paris', 'Quanto ao temperamento, o Bulldog Francês é extremamente afetuoso, companheiro e sociável. É uma raça que adora estar por perto da família e costuma se dar bem com crianças, outros cães e até mesmo com gatos, quando acostumado desde cedo.', 'img/bulldogfrances.jpg'),
(11, 'Pug', 'O Pug é uma raça antiga originária da China, onde era mascote de imperadores há cerca de 2.000 anos, com registros de cães semelhantes já no século IV a.C. Chegou à Europa no século XVII, pela rota dos holandeses. ', ' De construção quadrada, focinho achatado, cabeça grande, olhos expressivos, rabo enroscado e pelagem curta, o Pug é atuado mais como companhia — afetuoso, brincalhão, adaptável e tranquilo', 'img/pug.jpg'),
(12, 'Cirneco Dell Etna', 'Originário da Sicília, o Cirneco dell’Etna é uma raça muito antiga, usada há milênios para caçar coelhos nas encostas do vulcão Etna. Seus ancestrais possivelmente vieram com os fenícios e lembram os cães do Egito Antigo. Quase extinto no século XX, foi recuperado nos anos 1930 e reconhecido oficialmente em 1956.', 'É um cão de porte pequeno, esguio, com pelagem curta em tons areia, castanho ou avermelhado, e orelhas grandes e eretas. Inteligente, ágil e com energia média a alta, é leal com a família, mas pode ser reservado com estranhos. Requer exercícios diários e cuidados simples, especialmente com as orelhas.', 'img/cirneco.jpg'),
(13, 'Boston Terrier', 'O Boston Terrier surgiu no final do século XIX, em Boston, nos Estados Unidos, a partir de cruzamentos entre Bulldogs e Terriers. Criado inicialmente para lutas, logo foi refinado até se tornar um cão de companhia elegante e amigável. Em 1893, foi oficialmente reconhecido pelo American Kennel Club, sendo uma das primeiras raças desenvolvidas nos EUA.', 'É um cão de porte pequeno a médio, com corpo compacto, pelagem curta e brilhante, geralmente preta e branca. Possui focinho curto, olhos expressivos e orelhas eretas. Afetuoso, inteligente e sociável, adapta-se bem a apartamentos e convive com crianças e outros animais. Tem energia moderada, mas precisa de companhia constante. Por ser braquicefálico, requer cuidados com calor e exercícios intensos.', 'img/bostonterrier.jpg'),
(14, 'Perro Peruano Sem Pelo', 'Originário do Peru, o Perro Peruano Sem Pelo é uma raça ancestral, com registros que remontam às civilizações pré-incaicas, como a Moche e a Chimú, onde era representado em cerâmicas e artefatos sagrados. Considerado um cão sagrado pelos povos antigos, quase desapareceu após a colonização espanhola, mas foi redescoberto no século XX e reconhecido oficialmente como Patrimônio Cultural do Peru em 2001.', 'É um cão de porte pequeno, com corpo esguio, elegante e totalmente sem pelos — embora alguns tenham pequenas mechas na cabeça, patas ou cauda. A pele é lisa e quente ao toque, em cores variadas. Inteligente, sensível e afetuoso com a família, pode ser reservado com estranhos. Possui energia média, adapta-se bem a ambientes internos e requer cuidados com a pele, como proteção solar e hidratação. É hipoalergênico e silencioso, sendo ideal para quem busca um cão discreto e próximo.', 'img/perroperuano.jpg'),
(15, 'Basset Hound', 'Originário da França, o Basset Hound surgiu na Idade Média como um cão de caça a pé, ideal para seguir rastros no chão devido ao seu faro apurado e corpo baixo. No século XIX, a raça foi aprimorada na Inglaterra e se popularizou nos Estados Unidos, sendo reconhecida oficialmente em 1885.', 'É um cão de porte pequeno, corpo alongado, patas curtas, orelhas longas e pele solta. Tem pelagem curta, geralmente tricolor ou bicolor. É afetuoso, calmo e sociável, embora teimoso e guiado pelo faro. Possui energia média, exige caminhadas regulares e cuidados com pele e ouvidos.', 'img/bassethound.jpg'),
(16, 'Griffon', 'Originário da Bélgica no século XIX, o Griffon de Bruxelas foi inicialmente usado para caçar ratos em estábulos e logo se tornou popular como cão de companhia, especialmente entre a nobreza. Teve impulso com o apoio da Rainha Marie-Henriette e foi reconhecido oficialmente na Europa e internacionalmente.', 'É um cão pequeno, com focinho curto, olhos grandes e expressão marcante, podendo ter pelagem lisa ou dura. Inteligente, sensível e muito apegado ao tutor, pode ser desconfiado com estranhos. Tem energia média, adapta-se bem a ambientes internos e requer socialização e cuidados regulares com a pelagem.', 'img/griffon.jpg'),
(17, 'Basenji', 'O Basenji é uma das raças caninas mais antigas do mundo. Há registros de animais semelhantes em artefatos egípcios datados de mais de 4 000 anos. Originário da África Central, foi tradicionalmente utilizado por tribos locais em atividades de caça — particularmente para rastrear aves e pequenos animais, com o auxílio de coleiras com guizos e ossos de macaco', 'É uma raça porte médio e possui pelagem curta nas cores: vermelho e branco, preto e branco, tricolor ou tigrado, com marcas brancas em peito, patas e ponta da cauda. Muito inteligente, energizado, alta energia e curiosidade. Em geral, é reservado com estranhos, mas fiel e protetor com a família', 'img/basenji.jpg'),
(19, 'Poodle Toy', 'Originário possivelmente da Alemanha ou França, o Poodle foi desenvolvido a partir dos séculos XV–XVII para a caça aquática, com suas variantes Toy surgindo mais tarde como cães de companhia e desfile.', 'É um cão toy elegante, leve e compacto, com pelagem encaracolada e densa. Extremamente inteligente, cheio de energia e fácil de treinar, exige escovação regular. Leal, vivaz e adaptável, se dá bem em ambientes internos.', 'img/poodletoy.jpg'),
(20, 'Corgi', 'Criado no País de Gales há centenas de anos para pastoreio de ovelhas, ganhou fama mundial com a Rainha Elizabeth II, que possuía dezenas e ajudou a popularizar a raça', 'Baixo, robusto e ágil, com orelhas eretas e cauda curta. Inteligente, leal e ativo, precisa de atividades diárias. Cativa pela personalidade forte e afetuosa, e adora aventuras ao ar livre .', 'img/corgi.jpg'),
(21, 'Papillon', 'De origem europeia (França/Bélgica), o Papillon é descendente de pequenos spaniels usados pela nobreza nos séculos XVII–XVIII, reconhecido pela sua pelagem característica e elegância.', 'Cão de porte toy, leve, com pelagem longa, franjada nas orelhas que formam “asas”. Inteligente, alerta e adorável em agility e obediência, sociável e ideal para lares variados.', 'img/papillon.jpg'),
(22, 'Spitz', 'Tipo antigo de cães domésticos originários de regiões frias (Ártico/Sibéria), com representações em cerâmicas de forma antiga .', 'De orelhas pontudas, cauda enrolada e dupla pelagem que protege do frio. Varia em porte (do Pomeranian ao Malamute). São inteligentes, alertas, independentes e exigem socialização e exercício .', 'img/spitz.jpg'),
(23, 'Havanês', 'Raça nacional de Cuba, descendente de pequenos cães trazidos por colonizadores espanhóis, desenvolvida no século XIX como companhia da aristocracia.', 'Pequeno, pelagem macia e sedosa, muitas vezes em tons variados. Amigável, inteligente, apegado, adora estar com o tutor. Requer escovação regular, adapta-se bem a ambientes internos.', 'img/havanes.jpg'),
(24, 'Russian Tsvetnaya Bolonka', 'Desenvolvida em Moscou e São Petersburgo no século XIX–XX, cruzando pequenas raças importadas com cães locais. Tornou-se popular após a queda da URSS, reconhecida pela AKC em 2014 .', 'Cão toy de corpo compacto, com pelagem longa e ondulada, não solta pelos. Amigável, equilibrado, ideal para apartamentos, alerta, inteligente e fácil de treinar .', 'img/russian.jpg'),
(25, 'Coton de Tulear', 'Originário de Madagascar, acredita-se que descendentes de cães europeus náufragos formaram essa raça. Presente na ilha desde séculos atrás, foi reconhecido pelo AKC em 2014 .', 'Cão pequeno e robusto, pelagem branca semelhante a algodão. Afetuoso, brincalhão, adaptável, fiel, é hipoalergênico, exige escovação frequente e boa dose de exercício .', 'img/coton.jpg'),
(26, 'Japanese Chin', 'Descendente de cães levados da China à corte imperial do Japão por volta do século VII. Tornou-se popular entre a nobreza e, no Ocidente, desde o século XIX .', 'Toy elegante, pelagem longa e sedosa, expressão delicada. Inteligente, independente, ás vezes comparado a gatos por comportamento. Afável, adaptado a apartamentos, fácil de treinar e ideal para terapia ou companhia .', 'img/japanese.jpg'),
(27, 'Yorkshire', 'Criado na Inglaterra no século XIX por operários de fábricas têxteis, cruzando terriers escoceses para caçar ratos. Tornou-se um cão de companhia sofisticado e reconhecido pelo AKC em 1885 .', 'Toy pequeno com longe e sedosa pelagem azul-acizentada e dourada. Enérgico, confiante, leal e alerta. Inteligente mas teimoso, requer escovação diária, caminhada diária e vive bem em ambientes pequenos .', 'img/york.jpg'),
(29, 'Shitzu', 'De origem tibetana, nascido do cruzamento entre Lhasa Apso e Pekingese, o Shih Tzu tornou-se cão de palácio chinês já no século XIV. Foi preservado pela imperatriz Cixi e quase extinto após 1949; a raça moderna deriva de apenas 14 cães trazidos à Europa entre 1928 e 1952. Reconhecido pelo AKC em 1969 ', 'De porte pequeno, pelagem longa e sedosa que cresce constantemente. É afetuoso, sociável, calmo, com energia baixa a moderada. Adapta-se bem a ambientes internos, exige escovação e cuidados regulares com olhos e focinho braquicefálico .', 'img/shitzu.jpg'),
(30, 'Maltês', 'Raça antiga originária da região do Mediterrâneo, possivelmente utilizada já no século II a.C. para companhia. Ganhou popularidade na Europa renascentista e é referência entre cães toy hipoalergênicos .', 'Pequeno, todo branco, com pelagem longa e sedosa. Temperamento doce, brincalhão, adaptável a espaços pequenos. Energia baixa, requer escovação diária e atenção à pele sensível.', 'img/maltes.jpg'),
(31, 'Chihuahua pelo longo', 'Pequena raça mexicana, possivelmente descendente de cães antigos mesoamericanos. Popularizou-se como companhia nos EUA a partir do início do século XX.', 'Extremamente pequeno, atlético, com pelagem longa fluída. Temperamento alerta e corajoso, mas de energia baixa e propenso a apego intenso. Ideal para ambientes internos, mas exige socialização precoce.', 'img/chihuahualongo.jpg'),
(32, 'Skye Terrier', 'Originado há mais de 400 anos na Ilha de Skye (Escócia), usado para caça a animais em tocas. Foi raça da realeza após ser adotado por Rainha Vitória em 1842. Hoje é raro e considerado em risco', 'De porte baixo, com pelagem dupla longa que protege do clima. Leal, reservado, de energia baixa a moderada. Exige caminhada diária (~1 hora) e escovação regular .', 'img/skye.jpg'),
(33, 'Cairn Terrier', 'Proveniente das Terras Altas e da Ilha de Skye (Escócia), usado por mais de 200 anos para caçar roedores em pilhas de pedra (“cairns”). Reconhecido pelo AKC em 1903.', 'Pequeno, robusto, com pelagem áspera e dupla. Corajoso, brincalhão, inteligente, de energia moderada (baixa para atividades leves). Precisa de escovação e estimulação diária “psicológica” .', 'img/cairn.jpg'),
(34, 'Pequinês', 'Raça chinesa venerada desde a dinastia Tang (VII–X), usada como companhia na corte imperial. Introduzida no Ocidente no início do século XX após a invasão de Pequim .', 'Pequeno, compacto, com pelagem longa e volumosa. Temperamento orgulhoso, leal, calmo e de energia baixa. Precisa de escovação frequente, cuidado respiratório por ser braquicefálico.', 'img/pequines.jpg'),
(35, 'Dachshund pelo longo', 'Originado na Alemanha no início do século XVIII para caçar texugos (“Dachs‑Kriecher”). A variedade de pelo longo surgiu de cruzamentos com spaniels no século XIX .', 'Corpo longo, pernas curtas, pelagem longa e sedosa. Temperamento corajoso, teimoso, mas com energia baixa a moderada. Requer caminhadas regulares e cuidados com coluna.', 'img/dachshundlongo.jpg'),
(36, 'Bichon Frisé', 'Originário das Ilhas Canárias e difundido na corte europeia no século 13. Sobreviveu à Revolução Francesa com artistas de rua e foi reconhecido pela FCI em 1959 .', 'Pequeno, pelagem branca encaracolada, hipoalergênico. Temperamento alegre, sociável, de energia baixa a moderada. Exige escovação, tosa regular e atividade leve diária .', 'img/bichon.jpg'),
(37, 'Cavalier King Charles Spaniel', 'Descendente dos toy spaniels da corte de Carlos I e II na Inglaterra (séculos XVII). Redesenvolvido nos anos 20 para recuperar o tipo antigo e reconhecido como raça separada em 1945 (UK) e 1996 (AKC).', 'Pequeno a médio, pelagem longa e sedosa em várias cores. Temperamento extremamente afetuoso, sociável, tranquilo e de energia baixa. Exige escovação, companhia constante e cuidado com predisposição a doenças cardíacas .', 'img/cavalier.jpg'),
(38, 'Affenpinscher', 'Originado na Alemanha como caçador de ratos em estábulos, evoluiu para cão de companhia por volta do século XIX e XX. O nome significa “macaco em miniatura”.', 'Toy robusto com pelagem áspera e expressão de macaco. Temperamento corajoso, curioso, leal e um pouco teimoso. Energia baixa a moderada. Precisa de escovação ocasional e atenção aos brinquedos por ser territorial .', 'img/affen.jpg'),
(62, 'Beagle', 'O Beagle tem origens antigas, com registros de cães semelhantes desde a Grécia Antiga. A raça moderna foi desenvolvida na Inglaterra durante o século XVIII, onde ganhou fama como um excelente cão de caça a lebres. Tornou-se popular entre a nobreza britânica e, posteriormente, nos Estados Unidos, sendo reconhecido oficialmente pelo American Kennel Club (AKC) em 1885.', 'É um cão de porte médio, com pelagem curta e densa, geralmente tricolor (preto, marrom e branco) ou bicolor. Muito sociável, alegre, curioso e ativo, o Beagle é conhecido pelo excelente faro e pela teimosia. Convive bem com crianças e outros cães, mas precisa de estímulo mental e físico constante para evitar comportamentos destrutivos.', 'img/beagle.jpg'),
(63, 'Dálmata', 'Originário da região da Dalmácia, atual Croácia, o Dálmata aparece em registros artísticos desde o século XVI. No século XVII, passou a ser usado na Inglaterra como cão de carruagem e, mais tarde, tornou-se símbolo dos bombeiros. Ganhou grande notoriedade com o filme “101 Dálmatas”, da Disney, em 1961.', 'De porte médio a grande, o Dálmata tem pelagem branca com manchas arredondadas pretas ou marrons. É enérgico, inteligente e afetuoso, com tendência a formar laços fortes com a família. Requer exercícios diários e socialização desde filhote. Pode ser reservado com estranhos e tem sensibilidade auditiva (alguns exemplares podem apresentar surdez).', 'img/dalmata.jpg'),
(64, 'Boxer', 'O Boxer foi desenvolvido na Alemanha no século XIX, a partir do antigo Bullenbeisser (um cão de caça a grandes animais) cruzado com Bulldogs ingleses. Era usado como cão de guarda e em guerras, além de se destacar como cão policial e de companhia. Seu padrão moderno foi estabelecido no início do século XX.', 'De porte médio, musculoso e atlético, possui pelagem curta nas cores dourada (amarela) ou tigrada, geralmente com máscara preta. É um cão brincalhão, protetor, dócil com a família e excelente com crianças. Muito energético, precisa de exercícios diários e atenção constante. Também pode ser teimoso e impulsivo se não for bem socializado.', 'img/boxer.jpg'),
(65, 'Whippet', 'O Whippet surgiu no norte da Inglaterra no século XIX como uma versão menor do Greyhound, criado por operários para caçar pequenos animais e participar de corridas. Sua popularidade cresceu devido à velocidade e porte compacto. A raça foi oficialmente reconhecida em 1891 pelo Kennel Club britânico.', 'É um cão elegante e atlético, de porte médio e pelagem curta e fina, disponível em diversas cores. Pode atingir até 60 km/h, sendo muito veloz para seu tamanho. Dentro de casa, é calmo, afetuoso e silencioso. Requer exercícios regulares e cuidados com temperaturas frias, devido à sua baixa gordura corporal.', 'img/whippet.jpg'),
(66, 'Pastor Belga Malinois', 'Originário da Bélgica, o Pastor Belga Malinois surgiu no final do século XIX como uma das quatro variedades do Pastor Belga. Ele foi criado com foco em versatilidade, especialmente para pastoreio e guarda. Com o tempo, destacou-se pelo desempenho em funções policiais e militares, sendo muito utilizado em todo o mundo em atividades de proteção, busca e resgate.\r\n', 'É um cão de porte médio, com pelagem curta fulvo-encarvoada e máscara preta na face. Extremamente inteligente, leal, vigilante e ágil, o Malinois precisa de adestramento, estímulo mental e exercícios intensos. Não é recomendado para tutores inexperientes, pois exige liderança e atividades regulares para se manter equilibrado.', 'img/pastorbelga malinois.jpg'),
(67, 'Boiadeiro Australiano', 'Desenvolvido na Austrália no século XIX para pastorear gado em grandes propriedades, a partir de collies, dingos e outros cães de trabalho. Reconhecido pelo AKC em 1980', 'Cão de porte médio com pelagem dupla azul ou avermelhada salpicada. Inteligente e leal, mas demanda exercícios físicos e mentais diários. Combina energia moderada com comportamento equilibrado em família.', 'img/boiadeiroaust.jpg'),
(68, 'Spitz Finalndês', 'Raça ancestral da Finlândia, usada há três mil anos para caça de aves. Sobreviveu graças ao trabalho de preservação no século XIX e foi oficializada em 1892, tornando-se o cão nacional em 1979', 'Médio porte, pelagem dupla e orelhas e cauda típicas de spitz. Ativo e vocal, com energia moderada a alta; exige caminhadas diárias e estimulação mental. Inteligente, independente e reservado com estranhos ', 'img/spitzifilan.jpg'),
(69, 'American Bully', 'Criada nos EUA nos anos 1990 a partir de American Staffordshire Terrier, Bulldogs e Pit Bulls, com foco em equilíbrio entre robustez e apego familiar. Oficializada em 2004 pelo ABKC', 'Porte médio-baixo, musculoso, com cabeça larga. Temperamento dócil, calma e sociável, ideal para família. Energia baixa a moderada, requer caminhadas diárias e atenção ao comportamento.', 'img/american.jpg'),
(70, 'Elkhound Norueguês', 'Raça antiga usada por vikings para caçar grandes animais como alces e ursos, com raízes no período neolítico. Reconhecido pelo AKC em 1913 ', 'Cão de porte médio, pelagem dupla cinza. Leal, alerta, inteligente e familiar, mas independente. Energia moderada, precisa de exercício diário e socialização. Ótimo guardião. .', 'img/elkhound.jpg'),
(71, 'Dogue Brasileiro', 'Desenvolvido no Brasil nos anos 1970 pelo cruzamento de Bull Terrier com Boxer e American Staffordshire Terrier. Reconhecido pela CBKC em 1999 \r\n', 'Mediumo porte, forte e ágil, com pelagem curta ou média. Temperamento equilibrado e protetor, leal à família. Energia moderada, adapta-se bem à vida urbana com exercícios regulares.', 'img/doguebrasi.jpg'),
(72, 'Buldogue Campeiro', 'Originário do Brasil colonial (século XVIII), utilizado para domar gado e proteger carroças. Quase extinto, foi reconhecido pela CBKC em 2001 ', 'Cão de porte médio-grande, musculoso e resistente. Corajoso, fiel, mas tranquilo. Energia baixa, requer pouca atividade intensa e é excelente para guarda.', 'img/buldoguecam.jpg'),
(73, 'Staffordshire Bull Terrier', 'Desenvolvido na Inglaterra no século XIX, descendente de Bull Terrier e Bulldog, criado como cão de luta e depois transformado em cão de companhia pela classe trabalhadora. Reconhecido como raça oficial no século XIX.', 'Pequeno a médio porte, musculoso e robusto. Temperamento amigável, leal e corajoso, conhecido por sua tolerância com crianças. Energia baixa a moderada, precisa de exercícios leves e socialização.', 'img/staffordshire.jpg'),
(74, 'Bulldog Inglês', 'Originário da Inglaterra, usado inicialmente em brigas de touros (bull baiting) até o fim dessa prática no século XIX. A raça foi então refinada para companhia, mantendo-se popular e reconhecida pelo AKC em 1886 .', 'De porte médio, corpo robusto e focinho achatado. Apelidado de “cão de colo”, é tranquilo, afetuoso e ideal para apartamentos. Energia baixa, requer caminhadas curtas e cuidados com calor e pele devido à estrutura braquicefálica .', 'img/bulldogingles.jpg'),
(75, 'Bull Terrier', 'Originado na Inglaterra no século XIX, o Bull Terrier foi criado a partir do cruzamento entre Bulldogs e terriers para esportes sangrentos. Posteriormente, James Hinks refinou a raça, introduzindo traços mais elegantes e a característica cabeça oval. De cão de combate, tornou-se popular como cão de companhia, sendo reconhecido oficialmente e adotado amplamente por famílias.', 'De porte médio, musculoso e com cabeça oval única, o Bull Terrier possui pelagem curta (branca ou colorida) e personalidade brincalhona, leal e teimosa. É afetuoso com a família, mas precisa de socialização desde cedo. Tem energia alta e exige exercícios diários. Pode ter predisposição à surdez, doenças cardíacas e de pele. Vive, em média, de 12 a 13 anos.', 'img/bullterrier.jpg'),
(76, 'Border Collie', 'Desenvolvido na fronteira entre Inglaterra e Escócia como cão de pastoreio altamente eficiente. É considerado a raça mais inteligente e focada em tarefas. ', 'De porte médio, ágil e atlético. Altamente inteligente e com energia intensa, requer 2–3 horas diárias de exercícios físicos e mentais. Muito dedicado ao trabalho, precisa de estímulos constantes.', 'img/bordercollie.jpg'),
(77, 'Pastor de Shetland', 'Originário das Ilhas Shetland (Escócia), para pastorear ovelhas em clima rigoroso. Formalmente reconhecido em 1909.', 'Pequeno, com pelagem longa e densa. Inteligente, alerta e dócil. Energia moderada, requer exercícios diários e estimulação mental. Protetor, pode ser vocal.', 'img/pastordhetland.jpg'),
(78, 'Cocker', 'Desenvolvido na Inglaterra como cão de caça a aves (woodcock). Tornou-se popular e separado em variedades inglesa e americana no início do século XX.', 'Pequeno a médio porte, corpo compacto e pelagem sedosa com franjões. Alegre, afetuoso e ativo, com energia moderada. Requer caminhada diária e cuidados com a pelagem e orelhas.', 'img/cocker.jpg'),
(79, 'Hound Afegão', 'Originário das montanhas do Afeganistão, uma das raças mais antigas. Usado historicamente para caça com velocidade e resistência.', 'Alto, esguio, com pelagem longa e fina. Independente, elegante e um pouco reservado. Energia moderada, precisa de corridas periódicas. Requer escovação frequente devido ao pelo longo.', 'img/afegao.jpg'),
(80, 'Collie Barbado', 'Raça britânica antiga usada para pastoreio de ovelhas. Perto da extinção em meados do século XX, foi reabilitado e reconhecido por volta de 1955–59. ', 'Médio porte, pelagem longa, densa e desgrenhada (aparência “barbuda”). Inteligente, sociável e ativo, com energia moderada. Gosta de atividade ao ar livre, precisa de escovação diária e estimulação mental.', 'img/colliebarbudo.jpg'),
(81, 'Pastor Australiano', 'Embora seu nome sugira outra origem, foi desenvolvido nos EUA como cão de pastoreio. Reconhecido pela ANKC em 1994.', 'Médio porte, musculoso, com pelagem variada. Muito inteligente, leal e energético (energia média-alta), precisa de trabalho e exercícios. Excelente em esportes caninos.', 'img/pastoraustraliano.jpg'),
(82, 'Mudi', 'Raça húngara descoberta e nomeada em 1936. Quase extinta na II Guerra Mundial, mas reconhecida pela FCI em 1966 e pela AKC em 2022. ', 'Médio porte, pelagem ondulada. Muito ativo, inteligente e leal. Requer exercícios vigorosos diários (corridas, esportes). Sucesso em agility, obediência e pastoreio.', 'img/mudi.jpg'),
(83, 'Cão Pastor dos Pirenéus', 'Raça francesa antiga usada para pastorear ovelhas nos Pirineus, com milhares de anos de tradição.', 'Pequeno-médio porte, pelagem média a longa. Muito inteligente e alerta, com energia moderada a alta. Ótimo em pastoreio e esportes, precisa de estímulo constante.', 'img/pastorpireneus.jpg'),
(84, 'Poodle médio', 'Descendente de cães de água europeus (França/Alemanha), desenvolvido como cão de companhia e desempenho.', 'Médio porte, pelagem encaracolada hipoalergênica. Extremamente inteligente, obediente e ágil. Energia moderada, requer tosa, mental e físico estimulantes (agility, obediência).', 'img/poodlemedio.jpg'),
(85, 'Hovawart', 'Raça alemã antiga de cão de fazenda. Quase desapareceu no século XX e foi reconstituída com várias raças de trabalho, reconhecida em 1937.', 'Médio a grande porte, pelagem longa. Leal, protetor e inteligente. Energia moderada. Ideal para guarda, busca e resgate. Requer socialização e exercícios regulares.', 'img/hovawart.jpg'),
(86, 'Cão Finlandês da Lapónia', 'Raça da Finlândia usada tradicionalmente para pastorear renas.', 'Médio porte, resistente ao frio. Extremamente inteligente, alerta e ativo. Energia alta: exige mais de 1h de atividade diária, excelente em esportes e desafios mentais.', 'img/laponia.jpg'),
(87, 'Eurasier', 'Desenvolvido na Alemanha em 1960 a partir de Chow Chow, Wolfspitz e Samoyed. Reconhecido pela FCI em 1973. ', 'Médio porte, pelagem densa. Calmo e reservado com estranhos, muito apegado à família. Energia moderada, tranquilo em ambientes internos, precisa de companhia humana e exercícios leves.', 'img/eurasier.jpg'),
(88, 'Keeshond', 'Raça holandesa do século XVII–XVIII usada como cão de barcaça e símbolo político. Chegou à Inglaterra em 1905 e à AKC em 1930.', 'Médio porte, pelagem espessa, aparência sorridente. Inteligente e afetuoso, de energia baixa a média. Precisa de passeios moderados e escovação duas vezes por semana.', 'img/keeshond.jpg'),
(89, 'Chow Chow', 'Raça chinesa ancestral, datada de até 206 a.C., usada como cão de guarda e caça. Introduzido ao Ocidente no século XVIII e reconhecido pelo AKC em 1903.', 'Médio porte, pelagem dupla e olhos com porte de leão, língua azul-negra. Independente, reservado e leal. Energia baixa, precisa de passeios curtos. Requer escovação frequente e cuidado com saúde (quadril, olhos).', 'img/chowchow.jpg'),
(90, 'Komondor', 'Originário da Hungria, o Komondor é uma raça ancestral trazida pelos cumanos — um povo nômade das estepes asiáticas — por volta dos séculos XII e XIII. Criado para proteger rebanhos, especialmente de ovelhas, se destacava por sua pelagem que lhe permitia se camuflar entre os animais. É considerado um dos cães de guarda mais antigos da Europa.', 'De médio porte, o Komondor é facilmente reconhecido pelos longos cordões de pelo branco que cobrem todo o corpo, protegendo-o do frio e de ataques. É um cão calmo, mas muito vigilante, corajoso e independente. Possui energia média e precisa de exercícios diários e socialização desde filhote. É extremamente fiel à família, porém reservado com estranhos. Sua pelagem exige cuidados específicos e regulares.', 'img/komondor.jpg'),
(91, 'Labrador', 'Originário de Newfoundland (Canadá) no início do século XIX, o Labrador descendente do St. John’s Water Dog foi levado à Inglaterra, onde ganhou padrão e reconhecimento (AKC em 1917). Trabalhou com pescadores e em caça de aves aquáticas.', 'Cão atleticamente estruturado, 25‑36 kg, pelagem densa e curta, resistente à água nas cores preto, chocolate ou amarelo. Inteligente, amigável e extremamente ativo, requer cerca de 2 horas diárias de exercícios e atenção mental. Adaptável à família, bom com crianças, mas propenso a obesidade e displasia. Espírito de natação e trabalho intenso.', 'img/labrador.jpg'),
(92, 'Galgo Espanhol', 'Descende de sighthounds antigos (Saluki, Sloughi), presente na Espanha desde o século X ou mesmo trazido por fenícios há ~3 000 anos .Usado historicamente para caça e trabalho nobre.', 'Cão magro, elegante e veloz — ideal para caça. Temperamento afetuoso, calmo no lar e com instinto de caça alerta. Porte médio, pelagem curta ou áspera, precisa de exercícios moderados', 'img/galgoespa.jpg'),
(93, 'Weimaraner', 'Desenvolvido no início do século XIX na corte de Weimar (Alemanha), para caça de grandes presas como veado, urso e javali. Já era documentado em pinturas do século XVII, e foi reconhecido como raça distinta em 1891', 'Porte médio–grande, atlético, pelagem cinza-prateada. Extremamente inteligente, leal e energético — exige muita atividade física e mental. Bom para famílias ativas, mas pode desenvolver ansiedade e comportamentos destrutivos se entediado', 'img/weimaraner.jpg'),
(94, 'Pointer Inglês', 'Desenvolvido na Inglaterra no século XVIII a partir de cruzamentos entre cães de caça como Foxhound, Greyhound e Setters. Sua principal função era apontar e indicar a localização de aves abatidas para os caçadores.', 'Cão atlético, de porte médio a grande, conhecido por sua postura elegante ao farejar. É ativo, leal, sensível e amigável. Requer muito exercício físico e mental, sendo ideal para famílias com estilo de vida ativo.', 'img/pointer.jpg'),
(95, 'Rottweiler', ' Tem origem na Alemanha, descendente de antigos cães romanos usados para conduzir rebanhos e proteger os acampamentos militares. Seu nome vem da cidade de Rottweil, onde era usado como cão de açougueiro para puxar carroças e guardar dinheiro.', 'Físico robusto e musculoso, temperamento protetor, confiante e obediente com bom treinamento. Inteligente, exige socialização precoce e liderança firme. Muito leal à família e excelente cão de guarda.', 'img/rottweiler.jpg'),
(96, 'Doberman', 'Criado na Alemanha por Karl Friedrich Louis Dobermann no final do século XIX, cruzando várias raças (Rottweiler, Pinscher, Weimaraner, entre outras) para criar um cão de guarda versátil e confiável.', ' Porte médio-grande, corpo atlético, inteligente, vigilante e corajoso. Muito leal e protetor com sua família, com grande capacidade de adestramento. Precisa de estímulo físico e mental constante.', 'img/doberman.jpg'),
(97, 'Dogo Argentino', 'Desenvolvido na Argentina nos anos 1920 por Antonio Nores Martinez. Criado para caça de grandes animais como javalis e pumas, foi baseado principalmente no extinto Cão de Córdoba, além de outras raças como Mastiff e Boxer.', 'Forte, musculoso e resistente, com pelagem branca curta. É leal, corajoso e afetuoso com a família, mas precisa de socialização desde cedo. Pode ser dominante com outros cães.', 'img/dogo.jpg'),
(98, 'Cane Corso', 'Antiga raça italiana descendente dos molossos romanos, usada para guarda e caça de grandes animais. Quase extinta no século XX, foi resgatada por entusiastas nos anos 1970.', 'Cão de grande porte, musculoso e imponente. Inteligente, calmo, protetor e muito leal à família. Exige treinamento firme e socialização, sendo um excelente cão de guarda.', 'img/cane.jpg'),
(99, 'Boiadeiro Suiço', 'Originado nos Alpes suíços, utilizado tradicionalmente para pastoreio e tração. O Grande Boiadeiro Suíço é considerado o ancestral das demais variedades suíças de boiadeiros.', 'Forte, equilibrado e vigilante. Inteligente e obediente, muito ligado à família. Possui energia moderada, mas precisa de atividades regulares e espaço para se exercitar.', 'img/boiadeirosuico.jpg'),
(100, 'Rhodesian Ridgeback', 'Originário da África do Sul, criado por colonos para caçar leões e proteger propriedades. Resulta de cruzamentos entre cães europeus e cães indígenas africanos com uma característica faixa de pelos ao longo das costas.', 'Porte atlético, musculoso, cor dourada avermelhada. Independente, leal, silencioso e protetor. Necessita de espaço e exercícios, e responde bem ao adestramento consistente.', 'img/rhodesian.jpg'),
(101, 'Dogue de Bordeaux', 'Uma das raças francesas mais antigas, descendente de mastins romanos, utilizado para guardar propriedades e puxar cargas pesadas. Ganhou popularidade mundial após o filme “Turner & Hooch”.', 'Grande, forte e imponente, com cabeça larga e expressiva. Temperamento calmo, leal e protetor. Exige socialização precoce, é ótimo com a família, mas desconfiado com estranhos.', 'img/bordeaux.jpg'),
(102, 'Braco Alemão', 'Desenvolvido na Alemanha no século XIX como cão de caça versátil, combinando farejamento, apontar e recuperação de presas em terra e água.', 'Energético, inteligente e obediente. Requer estimulação física e mental intensa. Porte médio-grande, pelagem curta e fina. Ótimo para famílias ativas e caçadores.', 'img/braco.jpg'),
(103, 'Cão de São Humberto', 'Criado por monges da Abadia de São Humberto na Bélgica medieval, e refinado na Inglaterra. Utilizado por séculos para rastreamento de pessoas e animais.', 'Olfato extremamente apurado, com pele solta e orelhas longas. Carinhoso, tranquilo e persistente ao rastrear. Pode ser teimoso, mas muito dócil com a família.', 'img/humberto.jpg'),
(104, 'Dogue Alemão', 'De origem alemã, o Dogue Alemão (ou Great Dane) foi desenvolvido como cão de caça a javalis na Idade Média, descendendo de antigos molossos. Posteriormente tornou-se símbolo de status entre nobres europeus.', 'Muito grande e elegante, apesar do tamanho imponente tem temperamento calmo e gentil. É afetuoso, sociável e bom com crianças. Necessita de espaço e cuidados com articulações devido ao porte.', 'img/doguealemao.jpg'),
(105, 'Mastino Napolitano', 'Descende dos molossos da Roma Antiga, usados como cães de guarda e guerra. Desenvolvido no sul da Itália para proteção de propriedades, mantendo suas características históricas de imponência.', 'Enorme, musculoso, com pele solta e rugas profundas. Extremamente leal, territorial e reservado com estranhos. Apesar de aparência intimidadora, é dócil com sua família. Energia baixa e movimentos lentos.', 'img/mastino.jpg'),
(106, 'Mastiff', 'Uma das raças mais antigas da Grã-Bretanha, usada como cão de guerra, guarda e para entretenimento em arenas romanas. Foi refinada no século XIX como cão de companhia e proteção.', 'Muito grande e pesado, com temperamento calmo, nobre e protetor. Extremamente leal e gentil, mas reservado. Exige socialização desde cedo e adapta-se bem a ambientes tranquilos.', 'img/mastiff.jpg'),
(107, 'Shar-pei', 'Raça chinesa milenar usada para guarda e lutas, quase extinta no século XX durante o regime comunista. Resgatada por criadores nos EUA a partir de poucos exemplares remanescentes.', 'Porte médio, corpo robusto e pelagem curta. Caracterizado pelas dobras na pele. Independente, reservado e protetor, é leal à família e desconfiado com estranhos. Baixa energia e comportamento sereno.', 'img/shar.jpg'),
(108, 'Fila Brasileiro', 'Desenvolvido no Brasil colonial como cão de guarda, pastoreio e captura de escravos fugitivos. Resulta do cruzamento entre raças como Mastiff, Bloodhound e Bulldog.', 'Forte, de grande porte e extremamente territorial. Famoso por seu instinto de proteção (“avesso a estranhos”). Leal, corajoso e dócil com a família. Requer liderança firme e socialização precoce.', 'img/fila.jpg'),
(109, 'Golden Retriever', 'Desenvolvido na Escócia no final do século XIX por Lord Tweedmouth, a partir de cruzamentos entre retrievers, como o Tweed Water Spaniel, visando um cão para recuperar aves aquáticas ', 'De porte médio a grande, pelagem dourada densa, temperamento alegre, inteligente e afetuoso. Excelente em atividades familiares, assistência ou esportes caninos ', 'img/golden.jpg'),
(110, 'Collie', 'Originário da Escócia, sua linhagem surgiu do cruzamento entre cães romanos antigos e locais no século XIX; ganhou fama internacional por causa da Lassie ', 'Cão de porte médio, pelagem longa ou curta, estilo elegante. Muito inteligente, leal, ativo e excelente para pastoreio, precisa de estímulo físico e mental', 'img/collie.jpg'),
(111, 'Husky Siberiano', 'Criado pelos povos Chukchi na Sibéria para puxar trenós em condições árticas. Presente há milhares de anos, foi introduzido no Alasca em meados do século XIX e ajudou no \"resgate de Nome\"', 'De porte grande, pelagem densa, aparência de lobo. Temperamento amigável, independente, ativo e com grande resistência. Exige caminhada diária intensa', 'img/husky.jpg'),
(112, 'Setter Irlandes', 'Desenvolvido na Irlanda no século XIX por caçadores que buscavam cães de caça velozes com visão aguçada. Tornou-se popular em exposições por sua beleza.', 'Porte grande, pelagem sedosa ruiva, olfato e velocidade elevados. Alegre, ativo e bondoso, demanda atividades ao ar livre intensas', 'img/setter.jpg'),
(113, 'Pastor Alemão', 'Criado na Alemanha do século XIX por Max von Stephanitz para pastoreio, guarda, polícia e serviços agrícolas. Tornou-se padrão da raça moderna em 1899', 'Cão grande, musculoso e inteligente. Leal, versátil, com excelente temperamento para guarda, proteção e serviço, precisa de estímulo físico e mental', 'img/pastoralemao.jpg'),
(114, 'Pastor Belga', 'Desenvolvido na Bélgica no final do século XIX, com quatro variedades (Groenendael, Malinois, Tervuren, Laekenois), originadas como pastores e guarda‑rebanhos', 'Cão médio‑grande, ágil, alerta e leal. Excelente para trabalho policial, guarda e esportes caninos, requer treinamento firme e estimulação constante.', 'img/pastorbelga.jpg'),
(115, 'Akita Inu', 'Raça antiga da região de Akita (Japão). Usada para caça de javalis, urso e leões, reconhecida como símbolo de status e parte vital da cultura japonesa por mais de mil anos.', 'Cão grande, aparência imponente, pelagem dupla. Reservado, fiel e protetor da família. Necessita de socialização desde filhote e dono experiente', 'img/akitainu.jpg'),
(116, 'Briard', 'Originário da região francesa de Brie, com registros desde o século XIV. Usado originalmente para pastoreio e proteção de rebanhos, servindo até em missões militares', 'Cão grande com pelagem longa dupla. Inteligente, corajoso e protetor, excelente cão de guarda e companhia, com energia moderada-alta', 'img/briard.jpg'),
(117, 'Wolfhound irlandês', 'Raça ancestral da Irlanda, usada já antes do século III a.C. para caçar lobos e outros animais grandes. Quase extinta após a chegada dos colonos e a diminuição dos lobos, foi recriada no século XIX por George Augustus Graham cruzando com Deerhounds e outros cães grandes ', 'O maior cão da raça sighthound, com até 90 cm de altura. Temperamento dócil, gentil e calmo — descrito como “gigante gentil”. Possui pelagem dupla, precisa de exercícios diários, é paciente com crianças e requer socialização precoce', 'img/wolfhound.jpg'),
(118, 'Samoieda', 'Originado entre os povos Samoyede na Sibéria, empregado por milênios para conduzir trenós, pastorear renas e proteger acampamentos. O primeiro padrão foi levado à Inglaterra em 1889, com registro oficial em 1909', 'Cão de porte médio-grande com pelagem dupla branca espessa e a clássica “smiley”. Temperamento afetuoso, energético, sociável e brincalhão. Precisa de muita atividade e escovação constante', 'img/samoieda.jpg'),
(119, 'Bernese', 'Originário da região de Berna (Suíça), era usado para pastorear, puxar carroças e proteger fazendas desde a Idade Média. Raça reconhecida apenas no século XX, depois de quase desaparecer', 'Cão grande e robusto, com pelagem longa tricolor (preto, branco e dourado). Temperamento dócil, calmo, leal e excelente com famílias. Energia moderada — atividade diária suficiente para mantê-lo saudável', 'img/bernese.jpg'),
(120, 'Terra Nova', 'Desenvolvida na ilha de Newfoundland (Canadá) por pescadores, era usada para puxar redes, resgatar pessoas no mar e guardar barcos desde o século XIX', ' Cão grande e forte com pelagem densa resistente à água. Temperamento calmo, gentil, protetor e ótimo nadador. Exige exercícios moderados e cuidados com a pelagem dupla', 'img/terranova.jpg'),
(121, 'Borzoi', 'Também conhecido como Galgo Russo, foi desenvolvido nos campos russos no século XVII para caça de lobos. Cães da elite russa mantinham e cruzavam essa raça para manter a nobreza de sua forma e velocidade ', 'Cão de médio a grande porte, com pelagem longa e sedosa. Elegante, independente, reservado, mas leal. Energia moderada: adora correr, mas é tranquilo em casa .', 'img/borzoi.jpg'),
(122, 'Akbash', 'Raça turca ancestral, usada há milênios para proteger rebanhos contra predadores. O nome significa “cabeça branca” em turco, referência à sua coloração', 'Cão de grande porte, corpo branco, calmo e independente. Forte instinto protetor, leal à família e desconfiado com estranhos. Energia moderada — ideal para vigilância em áreas amplas .', 'img/akbash.jpg'),
(123, 'Cão de Montanha dos Pirinéus', 'Utilizado desde o século XVII nos Pirenéus (França/Espanha) para proteger rebanhos contra lobos e ursos. Raça tradicional de pastoreio com histórias relacionadas a monastérios e nobres', 'Forte, imponente e com pelagem branca dupla espessa. Temperamento calmo, vigilante e afetuoso com a família. É silencioso, reservado com estranhos e requer escovação frequente', 'img/montanha.jpg'),
(124, 'São Bernardo', 'Originado nos Alpes suíços por volta do século XVII por monges no hospice de São Bernardo para resgates de montanha. A raça foi aperfeiçoada por Cruz Vermelha suíça para salvar viajantes perdidos em nevascas', 'Cão gigante, bondoso, calmo e paciente. Resistência ao frio e ótima capacidade de resgate. Precisa de exercícios leves, socialização moderada e escovação regular .', 'img/bernardo.jpg');

--
-- Índices para tabelas despejadas
--

--
-- Índices de tabela `racas`
--
ALTER TABLE `racas`
  ADD PRIMARY KEY (`ID`);

--
-- AUTO_INCREMENT para tabelas despejadas
--

--
-- AUTO_INCREMENT de tabela `racas`
--
ALTER TABLE `racas`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=125;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
